site_name: GSX Hub
site_url: https://gsxhub.app
repo_url: https://github.com/GSX-Hub/App
repo_name: GSX-Hub/App

# Custom Homepage Elements
home_cover_image: assets/GSXHub_HD5I5Zg3N4.png # This path starts at your root mkdocs directory.
home_tagline: GSX Hub
home_description: |
  An installation / manager tool for GSX Profiles

# Gradient Color
home_gradient_hsla: hsla(224, 3%, 23%, 1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: Download   # Comment this parameter out to remove the button.
home_button1_url: https://github.com/GSX-Hub/App/releases/latest  # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"

home_button2_name: Docs   # Comment this parameter out to remove the button.
home_button2_url: /contribute/get-started/   # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"

theme:
  name: material
  custom_dir: material
  features:
  - search.suggest
  - header.autohide
  - announce.dismiss
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.indexes
  - navigation.instant
  - navigation.instant.progress 
  - content.code.annotate

  font:
    text: Poppins
    code: Roboto Mono
  logo: assets/Transparent.png
  favicon: assets/favicon.png

  plugins:
  - search
  - social
  - awesome-nav
  - git-revision-date-localized:
    enable_creation_date: true

  icon:
    repo: fontawesome/brands/github

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ubCkJQS6Mj
    - icon: fontawesome/brands/github
      link: https://github.com/GSX-Hub/App

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - FAQ: FAQ.md
  - Contribute:
    - Get Started: contribute/get-started.md
    - Profile Creators:
      - First Time Contributor: contribute/first-time-contributor.md
      - Returning Contributor: contribute/returning-contributor.md
      - Licensing: contribute/licensing.md
    - Profile Maintainers:
      - First Time Maintainer: contribute/first-time-maintainer.md
      - Returning Maintainer: contribute/returning-maintainer.md